### PR TITLE
add: Configuration Warnings and Asserts

### PR DESCRIPTION
**Pull request by ThePat02**
Add configuration warnings and asserts to the FSM and BT nodes.

### CODE REVIEW

**Comment by ThePat02** [comment]
Problem: Reset buttons on exported properties are randomly disappearing. Might be related to setter on exported properties with the type of node?

**Comment by ThePat02** [comment]
Bug not related. #48

**Comment by ThePat02** [comment]
I implemented some basic warnings for both FSM and BT.
@SirPigeonz Could you just check your project if any weird warnings show up on working trees? After that it should be ready to merge.

**Comment by SirPigeonz** [comment]
> I implemented some basic warnings for both FSM and BT. @SirPigeonz Could you just check your project if any weird warnings show up on working trees? After that it should be ready to merge.

Seems to work fine :)

**Comment by SirPigeonz** [comment]
@ThePat02 
Note. We just need to point in docs that if you extend nodes, you should add @tool in your script if you want warnings.
Also, extended nodes in the demo don't have updated scripts with @tool.

**Comment by ThePat02** [comment]
> @ThePat02 
> 
> Note. We just need to point in docs that if you extend nodes, you should add @tool in your script if you want warnings.
> 
> Also, extended nodes in the demo don't have updated scripts with @tool.

Good point. Also adding tool keyword to the templates. I am not sure if warnings work even without tool on scripts extending a tool script? Can't test it right now, but I remember fiddling around with this earlier.

**Comment by ThePat02** [comment]
> Note. We just need to point in docs that if you extend nodes, you should add @tool in your script if you want warnings.
Also, extended nodes in the demo don't have updated scripts with @tool.

Here are warnings working without the `@tool` keyword. This weirdly only applies to newly added nodes. Nodes from the example scene do not work...
image
image
Adding new ones enables the warnings again.
image

@SirPigeonz Any idea what causes this weird behaviour?

**Comment by SirPigeonz** [comment]
> @SirPigeonz Any idea what causes this weird behaviour?

I have no idea :D

**Comment by ThePat02** [comment]
> I have no idea :D

lol same

**Comment by ThePat02** [comment]
Adding asserts is postponed until #47 is implemented

**Pull request merged**
