### PR TITLE
add: Selectable process on FSM and BT node

### PR DESCRIPTION
**Pull request by ThePat02**

### CODE REVIEW

**Comment by SirPigeonz** [comment]
Yo! :) Hah you are fast. I wanted to do it today but thx for doing it! :)

> @SirPigeonz take a look at #27 and tell me what you think of it. Is that what you had in mind?
Yes, thats what I wanted to do. Although I have few tips to make it more performant in Godot.

Instead of using `if` to disable processing the rest of the block I think it's better to disable/enable required process callbacks.
Godot enables `_process()` and `_physics_process()` automatically if you add them to a Script, but you can disable them and enable them manually by running (usually in _ready() callback):
```gdscript
set_physics_process(bool)
set_process(bool)
```

This way you can controll which process is used for givan node even if both are present in the Script, saving some resources :)

Something like:
```gdscript
# No changes here
enum ProcessType {
    IDLE, ## Updates every frame, as often as possible.
    PHYSICS ## Updates on a fixed rate, 60 times per second by default. This is independent of your game's actual framerate, and keeps physics running smoothly
}


# Default PHYSICS and we can use setter to enable/disable callbacks
@export var process_type: ProcessType = ProcessType.PHYSICS:
	set(value):
		process_thread = value
		set_physics_process(process_thread == ProcessThread.PHYSICS)
		set_process(process_thread == ProcessThread.IDLE)


func _ready() -> void:
	# Setters are not run when var is initialized so we have to setup callbacks manually first on ready()
	set_physics_process(process_type == ProcessType.PHYSICS)
	set_process(process_type == ProcessType.IDLE)


func _physics_process(delta: float) -> void:
	_process_code(delta)


func _process(delta: float) -> void:
	_process_code(delta)


# This will be function that can be pasted in both callbacks, because only one of them will be run
# depending on process_type
func _process_code(delta: float) -> void:
	if not active:
		return

	blackboard.set_value("delta", delta)
	current_status = entry_point.tick(actor, blackboard)
```

**Comment by SirPigeonz** [comment]
Actually we can also skip:
```gdscript
if not active:
		return
```

And do something like this when eneable/disable process callbacks:
```gdscript
set_physics_process(active and process_type == ProcessType.PHYSICS)
set_process(active and process_type == ProcessType.IDLE)
```

This way process callback will be never even run when BTree is not `active`.

**Comment by ThePat02** [comment]
Feel free to open a PR yourself so you get the appropriate credit :)

These changes look good!

**Comment by SirPigeonz** [comment]
> Feel free to open a PR yourself so you get the appropriate credit :)
> 
> These changes look good!

Thx and sure thing! :) I will have some free time in the evening (Polish time) I will make a PR then.

**Comment by ThePat02** [comment]
Great. I will close this one then!

**Pull request closed without merging**
